development:
  adapter: postgresql
  encoding: unicode
  database: fitchike_development
  pool: 5
  username: mashype
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: fitchike_test
  pool: 5
  username: mashype
  password:

production:
  database: d5kk1o30ouuepv
  adapter: postgresql
  host: ec2-54-83-201-196.compute-1.amazonaws.com
  password: bBDJgoKn1yzDulvQIxdjnTtbkh
  